name: Render Thumbnail

on:
  push:
    paths:
      - 'shared/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Reason for manual execution'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute
      run: |
          echo "$GITHUB_WORKSPACE"
          cat $GITHUB_WORKSPACE/../shared/nyan-cat.json
          #docker run -v "$GITHUB_WORKSPACE/shared:/app/shared" -v "$GITHUB_WORKSPACE/thumbnails:/app/exported" thumbnail-render:latest

