name: Render Thumbnail
  
on:
  pull_request:
    paths:
      - 'shared/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Reason for manual execution'

permissions:
  contents: write
  pull-requests: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:thumbnails/render"
        file: Dockerfile
        push: false
        load: true
        tags: thumbnail-render:latest
        outputs: type=docker
    - name: Generate thumbnails
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          docker run -v "$GITHUB_WORKSPACE/shared:/app/shared" -v "$GITHUB_WORKSPACE/thumbnails:/app/exported" thumbnail-render:latest
          echo "Commiting changes on $GITHUB_HEAD_REF"
          git add .
          git commit -m "Update thumbnails"
          git push origin $GITHUB_HEAD_REF

