name: Render Thumbnail

on:
  push:
    paths:
      - 'shared/**'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Reason for manual execution'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: ls
